### ISSUE TITLE
IndexPageControllerの多言語環境でのエラー対応

### ISSUE THREAD

**Issue by mimimiku778** [pika-0203/Open-Chat-Graph#27]
`http://localhost:7000/tw`, `http://localhost:7000/th` にアクセスすると下記のエラーが発生する。
リコメンドの多言語対応にも関連する。

```
ErrorException: Trying to access array offset on false in /app/Controllers/Pages/IndexPageController.php(53): 
#0 /app/Controllers/Pages/IndexPageController.php(53): ExceptionHandler\{closure}(2, 'Trying to acces...', '/a...', 53)
#1 /shadow/Kernel/Dispatcher/ControllerInvoker.php(26): App\Controllers\Pages\IndexPageController->index(Object(App\Services\StaticData\StaticDataFile), Object(App\Models\CommentRepositories\RecentCommentListRepository), Object(App\Views\Schema\PageBreadcrumbsListSchema), Object(App\Services\Recommend\OfficialPageList))
#2 /shadow/Kernel/Kernel.php(121): Shadow\Kernel\Dispatcher\ControllerInvoker->invoke(Object(Shadow\Kernel\RouteClasses\RouteDTO))
#3 /shadow/Kernel/Kernel.php(34): Shadow\Kernel\Kernel->callController()
#4 /shadow/Kernel/Route.php(53): Shadow\Kernel\Kernel->handle(Object(Shadow\Kernel\RouteClasses\RouteDTO))
#5 /app/Config/routing.php(339): Shadow\Kernel\Route::run()
#6 /public/index.php(11): require_once('/a...')
#7 {main}
```

https://github.com/pika-0203/Open-Chat-Graph/blob/a6511ae0f633320448fdba106b1c5cd119a50ee5/app/Controllers/Pages/IndexPageController.php#L53

**Comment by mimimiku778** [comment]
https://github.com/pika-0203/Open-Chat-Graph/commit/ad2d8c572695ccdb816906bd25b9b95fed6e1614

データが空でfalseが返されたときにエラーが起きていたため修正・不要コードの削除を行った
リコメンドの静的ファイルの多言語対応との直接の依存性関係は無いため解決

**Comment by mimimiku778** [comment]
ListDtoがfalseの場合に起きる下記のエラーに対応する

```
ErrorException: Attempt to read property "type" on false in /app/Views/components/recommend_list2.php(9): 
#0 /app/Views/components/recommend_list2.php(9): ExceptionHandler\{closure}(2, 'Attempt to read...', '/a...', 9)
#1 /app/Helpers/functions.php(85): include('/a...')
#2 /app/Views/top_content.php(83): viewComponent('recommend_list2', Array)
#3 /shadow/Kernel/View.php(48): include('/a...')
#4 /shared/MimimalCMS_HelperFunctions.php(43): Shadow\Kernel\View->set('/top_content', Array)
#5 /app/Controllers/Pages/IndexPageController.php(56): view('top_content', Array)
#6 /shadow/Kernel/Dispatcher/ControllerInvoker.php(26): App\Controllers\Pages\IndexPageController->index(Object(App\Services\StaticData\StaticDataFile), Object(App\Models\CommentRepositories\RecentCommentListRepository), Object(App\Views\Schema\PageBreadcrumbsListSchema), Object(App\Services\Recommend\OfficialPageList))
#7 /shadow/Kernel/Kernel.php(121): Shadow\Kernel\Dispatcher\ControllerInvoker->invoke(Object(Shadow\Kernel\RouteClasses\RouteDTO))
#8 /shadow/Kernel/Kernel.php(34): Shadow\Kernel\Kernel->callController()
#9 /shadow/Kernel/Route.php(53): Shadow\Kernel\Kernel->handle(Object(Shadow\Kernel\RouteClasses\RouteDTO))
#10 /app/Config/routing.php(339): Shadow\Kernel\Route::run()
#11 /public/index.php(11): require_once('/a...')
#12 {main}
```

**Comment by mimimiku778** [comment]
ViewコンポーネントがListDto以外の型を考慮していないためViewに渡す前に対策をしたほうが簡単だと思われる
[app/Views/components/recommend_list2.php](https://github.com/pika-0203/Open-Chat-Graph/blob/ad2d8c572695ccdb816906bd25b9b95fed6e1614/app/Views/components/recommend_list2.php#L19)
[app/Views/components/open_chat_list_recommend.php](https://github.com/pika-0203/Open-Chat-Graph/blob/ad2d8c572695ccdb816906bd25b9b95fed6e1614/app/Views/components/open_chat_list_recommend.php)

**Comment by mimimiku778** [comment]
https://github.com/pika-0203/Open-Chat-Graph/commit/2516e8de8ad3fc9777a9bf3ba01eb0509028aa9

戻り値が `RecommendListDto|false` となる箇所をすべて空の RecommendListDto のみにした
空のRecommendListDtoをViewに渡されると空のリストがレンダリングされる
エラーの発生はなくなったためこれを仕様とする

**Comment by mimimiku778** [comment]
一部カテゴリで下記のエラーが発生する

RecommendListDtoのlistName(カテゴリ名)がHTMLエスケープを通って記号等の文字列が変わってしまうことが原因

```
ErrorException: Undefined array key "การเงิน &amp; ธุรกิจ" in /app/Views/components/recommend_list2.php(38): 
#0 /app/Views/components/recommend_list2.php(38): ExceptionHandler\{closure}(2, 'Undefined array...', '/a...', 38)
#1 /app/Helpers/functions.php(85): include('/a...')
#2 /app/Views/oc_content.php(223): viewComponent('recommend_list2', Array)
#3 /shadow/Kernel/View.php(48): include('/a...')
#4 /shared/MimimalCMS_HelperFunctions.php(43): Shadow\Kernel\View->set('/oc_content', Array)
#5 /app/Controllers/Pages/OpenChatPageController.php(163): view('oc_content', Array)
#6 /shadow/Kernel/Dispatcher/ControllerInvoker.php(26): App\Controllers\Pages\OpenChatPageController->index(Object(App\Models\Repositories\OpenChatPageRepository), Object(App\Views\Meta\OcPageMeta), Object(App\Services\Statistics\StatisticsChartArrayService), Object(App\Views\StatisticsViewUtility), Object(App\Views\Schema\PageBreadcrumbsListSchema), Object(App\Views\Schema\OcPageSchema), Object(App\Services\StaticData\StaticDataFile), Object(App\Services\Recommend\RecommendGenarator), Object(App\Models\CommentRepositories\RecentCommentListRepository), 130495, NULL)
#7 /shadow/Kernel/Kernel.php(121): Shadow\Kernel\Dispatcher\ControllerInvoker->invoke(Object(Shadow\Kernel\RouteClasses\RouteDTO))
#8 /shadow/Kernel/Kernel.php(34): Shadow\Kernel\Kernel->callController()
#9 /shadow/Kernel/Route.php(53): Shadow\Kernel\Kernel->handle(Object(Shadow\Kernel\RouteClasses\RouteDTO))
#10 /app/Config/routing.php(339): Shadow\Kernel\Route::run()
#11 /public/index.php(11): require_once('/a...')
#12 {main}
```

dd99dc394612773b7c61de8ffd021f73427657cf
RecommendListDto::listNameのエスケープ処理を回避して解決
